server:
  port: 8080
spring:
  rabbitmq:
    host: 192.168.137.183
    port: 9172
    username: tml
    password: 123456
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    virtual-host: /
